### ISSUE TITLE
Multiple Containers and obfuscated IDs Issue

### ISSUE THREAD

**Issue by joe-eklund** [linuxserver/docker-librespeed#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Running multiple containers that are load balanced results in result images not loading correctly. 
------------------------------

## Expected Behavior

I have the following setup:

HA Proxy in front of a two node Docker Swarm cluster, VM1 and VM2.

VM1 has a librespeed container and a postgres container.
VM2 has a librespeed container.

I should be able to run speedtests and load results pages and have them be consistent across the containers.

## Current Behavior

Issue 1:
Instead, what happens right now is HA Proxy load balances across the two librespeed containers to run speed tests. This works well, except that due to obfuscated ids, the results image pages are not consistent across the images. This results in sometimes a blank page when I am routed through the HA Proxy. When I access the container directly for the one that ran the speedtest in question, the results image loads correctly. When I look at the individual container results pages, they have different ids.

Issue 2:
Another related issue is that the obfuscated ids are changed every time I redeploy my stack. This means all previous results links will no longer work, as the ids have changed. One solution to this would be to be able to disable obfuscated ids, but I see that according to [bf2e0d5d085c8a59c2dc97c493c517304f66e8df/root/etc/cont-init.d/50-config#L35](https://github.com/linuxserver/docker-librespeed/blob/master/root/etc/cont-init.d/50-config#L35), this is hard coded to true. 

If this was turned into an environment variable that would be awesome and would fix both issues I believe. I see https://github.com/linuxserver/docker-librespeed/issues/14 has already asked for this, but I have not seen any progress.

## Steps to Reproduce

For issue 1 above:
1. Deploy two librespeed containers and one postgres container.
2. Setup postgres by importing the necessary sql file.
3. Load balance between the two containers using something like ha proxy, traefik, nginx, etc.
4. Run a speedtest.
5. Copy the image link and open in a new tab. Refresh a bunch and you will see sometimes it is blank.

For issue 2 above:
1. Deploy one librespeed container and one postgres container.
2. Setup postgres by importing the necessary sql file.
4. Run a speedtest.
5. Open the link to the image. It works.
6. Shutdown the stack and spin it back up.
7. Try the link again and it won't work due to ids being changed.

## Environment
**OS:** RHEL8
**CPU architecture:** x86_64
**How docker service was installed:** Official docker repo.

## Command used to create docker container (run/create/compose/screenshot)

Docker Stack File:

There are some environment variables there that this image doesn't use, I left them in because I was testing out the official image versus this one.
```
version: '3.7'
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    deploy:
      restart_policy:
        condition: any
      mode: global
    ports:
      - 8084:80
    environment:
      - TZ=America/Los_Angeles
      - MODE=standalone
      - TELEMETRY=true
      - ENABLE_ID_OBFUSCATION=false
      - REDACT_IP_ADDRESSES=false
      - PASSWORD=<redact>
      - EMAIL=<redact>
      - IPINFO_APIKEY=<redact>
      - DISABLE_IPINFO=false
      - DISTANCE=mi
      - DB_TYPE=postgresql
      - DB_NAME=librespeed
      - DB_HOSTNAME=postgres
      - DB_USERNAME=librespeed
      - DB_PASSWORD=<redact>
    volumes:
      - /librespeed/config-www:/config/www
    networks:
      - librespeed_internal
 
  postgres:
    image: postgres:14-alpine
    deploy:
      restart_policy:
        condition: any
    environment:
      - POSTGRES_USER=librespeed
      - POSTGRES_PASSWORD=<redact>
      - POSTGRES_DB=librespeed
      - TZ=America/Los_Angeles
    volumes:
      - /librespeed/postgres:/var/lib/postgresql/data
    networks:
      - librespeed_internal

networks:
  librespeed_internal:
```
