### ISSUE TITLE
No DB record is created - /result page isnt working

### ISSUE THREAD

**Issue by aronmgv** [linuxserver/docker-librespeed#8]
Hi,

- Using your latest image
- Configured DB to be `postgresql`
- Run script inside postgres container to initialize DB
- Tested via pgadmin, DB was created
- Run default `index.html` which has telemetry enabled by default (see it in the page source)
- No DB record is created

What might be the problem please? I would like to he DB records created and `/results` page working.. Thx, Michal

#### Docker-Compose.yml:
```yml
version: "3.7"

services:
  speedtest:
    container_name: speedtest.509.speedtest.80
    image: linuxserver/librespeed:latest
    restart: always
    ports:
      - 50980:80
    volumes:
      - $PWD/speedtest:/config
    environment:
      - PUID=1000
      - PGID=994
      - TZ=Europe/Prague
      - PASSWORD=vysledky
      - CUSTOM_RESULTS=true
      - DB_TYPE=postgresql
      - DB_NAME=speedtest
      - DB_HOSTNAME=postgres
      - DB_USERNAME=speedtest
      - DB_PASSWORD=************************
    labels:
      # AUTOUPDATE
      - com.ouroboros.enable=true
      # TRAEFIK 2
      - traefik.enable=true
      - traefik.http.routers.speedtest.entrypoints=websecure
      - traefik.http.routers.speedtest.rule=Host(`speedtest.example.com`)
      - traefik.http.routers.speedtest.service=speedtest
      - traefik.http.services.speedtest.loadbalancer.server.port=80

  postgres:
    container_name: speedtest.509.postgres.30
    image: postgres:9
    restart: always
    ports:
      - 50930:5432
    expose:
      - 5432
    volumes:
      - $PWD/postgres:/var/lib/postgresql/data
    environment:
      - PUID=1000
      - PGID=994
      - POSTGRES_DB=speedtest
      - POSTGRES_USER=speedtest
      - POSTGRES_PASSWORD=************************

  pgadmin:
    container_name: speedtest.509.pgadmin.81
    image: dpage/pgadmin4
    restart: always
    ports:
      - 50981:80
    volumes:
      - $PWD/pgadmin:/var/lib/pgadmin
    environment:
      - PUID=1000
      - PGID=994
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=************************

  adminer:
    container_name: speedtest.509.adminer.82
    image: adminer
    restart: always
    ports:
      - 50982:8080
    environment:
      - PUID=1000
      - PGID=994

networks:
  default:
    name: speedtest.509
 ```

#### Network in Developer Tools:
![image](https://user-images.githubusercontent.com/6546231/97096040-e9356d00-1666-11eb-8510-30e1f8d2e9f1.png)

#### Cannot access `/results` path:
![image](https://user-images.githubusercontent.com/6546231/97096058-20a41980-1667-11eb-8987-b6ef01693313.png)
